stages:
  - deploy

Deployment:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
  environment:
    name: production
    url: $HEROKU_APP_HOST
