# Generated by Django 2.2 on 2019-04-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GAConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generationEnd', models.IntegerField(default=150)),
                ('populationSize', models.IntegerField(default=20)),
                ('mutationRate', models.FloatField(default=0.2)),
            ],
        ),
    ]
